langauage: nodejs
node_js:
  - 16

services:
  - docker

install: 
  - echo "nothing needs to be installed"

before_script: 
  - echo "no tests"

script: 
  - docker --version
  - docker build -t simplenode .
  - docker tag simplenode chudah/simplenode:latest

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password=std-in
  - docker push chudah/simplenode